### ISSUE TITLE
Add navbar with dropdown on webstack template

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_webstack_poc#3]
Elements in Navbar:

- [x] Home (logo linking to home page)
- [x] WHY (about page)
- [x] LEARN : dropdown : PRODUCT; READ MORE (blog); KNOWLEDGE; COMMUNITY (TF forum)
- [x] PEOPLE : dropdown : TEAM; PARTNERS
- [x] MORE : dropdown : NEWSROOM; BLOG; FORUM; CONTACT; COMPANY

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/100634922-8ce5fd00-3338-11eb-9864-6fc4f0cd32cb.png)

**Comment by Vilnite** [comment]
We are missing dark/light switch mode.
